### ISSUE TITLE
Probelm with download at Xtra Anodyne Production

### ISSUE THREAD

**Issue by ravensghost** [dustin-lennon/Nova-External-RSS-Feed#2]
When downloaded from http://xtras.anodyne-productions.com/item/demonicpagan/rss-external-feed-application

Something seem wrong with the download. 

When I download (have done this three time now). 

I get a zip which is called rss-external-feed-application-1.0 and only  has a subfolder call Nova-External-RSS-Feed-2.-0.1 with a redme.md and a .gitignore file in it.

**Comment by dustin-lennon** [comment]
I have uploaded a new version to Xtras that contains the application folder

**Comment by ravensghost** [comment]
Thanks
